name: destination_catalog_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/alun.jpg
    - assets/images/alun1.jpg
    - assets/images/alun2.jpeg
    - assets/images/alun3.jpg
    - assets/images/flora.jpg
    - assets/images/flora1.jpg
    - assets/images/flora2.jpeg
    - assets/images/flora3.jpg
    - assets/images/lampu.jpeg
    - assets/images/lampu1.jpeg
    - assets/images/lampu2.jpg
    - assets/images/lampu3.jpg
    - assets/images/coban.jpg
    - assets/images/coban1.jpg
    - assets/images/coban2.jpg
    - assets/images/coban3.jpg
    

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 700
